### ISSUE TITLE
Why isn't the ciphertext at least as long as the ~key~ plaintext?

### ISSUE THREAD

**Issue by hatgit** [ph4r05/py-chacha20poly1305#1]
Given that ChaCha20 is a stream cipher that operates on each bit, I've read the ciphertext should be at least as long as the key (comparable to properties of the one-time-pad). However, using the  'test' bytearray python string in the example in this repositories Read me file, the resulting ciphertext is not as long as the key. I am wondering why is this and whether this is an error?

example code and output: 

```
import os
from chacha20poly1305 import ChaCha20Poly1305

key = os.urandom(32)
cip = ChaCha20Poly1305(key)

nonce = os.urandom(12)
ciphertext = cip.encrypt(nonce, b'test')

plaintext = cip.decrypt(nonce, ciphertext)
print('plaintex:',plaintext)
print('ciphertext:',ciphertext)
print('nonce:',nonce)
print('secret key:',key)
```
Example output: 

```
plain bytearray(b'test')
cip bytearray(b'G|W\xbbX\x15#\x94\x12\xff\xd6U\x8d\xb5T-m\xd0p$')
non b'\xce\xf6\xdb\xf2\xc47\xcc&\xc3b\xc9\x83'
key b'\x06\xb0\xbar\x89\xc3\xd7\xe66\x86h\xf0B\x81B\xbf\xbe\x11\xd3\x9e\xda\x9b\xf4\x90\xd0\xb2\x87\xc9S\x10\x1eM'
>>> 
```

**Comment by ph4r05** [comment]
better check lengths with the `len()` as this raw output prints some characters as hex-coded and some as ASCII, like '$' so the lengths are totally misleading.

```python
print('plaintex:',len(plaintext))
print('ciphertext:',len(ciphertext))
print('nonce:',len(nonce))
print('secret key:',len(key))

# Result:
plaintex: 4
ciphertext: 20
nonce: 12
secret key: 32
```

> the ciphertext should be at least as long as the key

This is not true. Ciphertext should be at least as long as the plaintext. 
Output from from chacha20poly1305.encrypt() is ciphertext (the same length as plaintext) + Poly1305 authentication tag. E.g., 4 + 16 = 20B.

**Comment by hatgit** [comment]
Thanks for the feedback here and pardon me, I meant 'as long as the plaintext', as per the [RFC 7539](https://tools.ietf.org/html/rfc7539) document which says: `The output is an encrypted message, or "ciphertext", of the same length.`

[Update] I see what you are saying the ciphertext was the same length but with the authentication tag of 16 bytes concatenated that is why the total is 20 bytes. Thanks for this info.
